// WARNING: This file was generated automatically by the Sauve Sails builder
// Do not make modifications to this file.  Modify other files in this directory
// and run the builder to recompile.
var MyDivView = function() {}////// AUTOGENERATED VIEW FROM mydiv.suave.html /////
MyDivView.prototype.generateHTML = function() {
__sout=""+"<div"+" id=\""+this.defField("root")+" >"+"\n   "+"<div"+" id=\""+this.defField("title")+" >"+" hllo there mate  "+"</div>"+"\n   "+"<div name=\"hihi!!\""+" />"+"\n"+"</div>"
return __sout; }
