require 'sails/sailsparse'
require 'sails/sailsnamer'
require 'pathname'
require 'erb'

module Sails
  module Config
  #configuration for an individual sail
    class Sail
      attr_accessor :directory, :dest_path, :class_name, :views, :other_files
      def initialize(src, dest, name)
        @directory = src
        @dest_path = dest
        @class_name = name
        @views = Array.new
        @other_files = Array.new
      end
    end
    class OtherFile
      attr_accessor :path, :include_order, :parent_config
      def initialize(parent, path, include_order = nil)
        @parent_config = parent
        @path = path
        @include_order = include_order
      end
    end
    class View
      attr_accessor :path, :jsname, :parent_config
      def initialize(parent, path, jsname = nil)
        @parent_config = parent
        @path = path
        @jsname = jsname
      end
      def jsname
        @jsname || parent_config.class_name + "View" #default view name
      end
    end
  end
  
  class Builder
    def build_sail(sail_config)
      if anything_to_compile?(sail_config)
        puts "Building sail #{sail_config.class_name} into #{sail_config.dest_path}.."
        dest = File.new(sail_config.dest_path, "w")
        incorporated_str = ""
        views_str = ""
        build_incorporated(sail_config, incorporated_str)
        build_views(sail_config, views_str)
        dest << ERB.new(File.new("sails/templates/built.template.rjs").read).result(binding)
        dest.fsync
        puts "wrote #{sail_config.class_name} to #{sail_config.dest_path}"
      end
    end
    
    def anything_to_compile?(sail_config)
      !sail_config.views.empty? #|| !sail_config.other_files.empty?
    end
    
    def build_views(sail_config, dest)
      sail_config.views.each do |view|
        $stdout << "   compiling view #{view.jsname} in file #{view.path}.. "
        generate_view_js(view.path, view.jsname, dest)
        $stdout.puts "finished."
      end
    end
    
    def build_incorporated(sail_config, dest)
      sail_config.other_files.each do |fconfig|
        $stdout << "   including #{fconfig.path} in output.. "
        dest << "//contents of '#{fconfig.path.basename}'\n"
        dest << File.new(fconfig.path, "r").read
        $stdout.puts "success."
      end
    end
    
    # generates the javascript to merge into the built file from a sails HTML file
    # @param view_name is the name of the class
    # @param dest is the output stream
    def generate_view_js(srcpath, view_name, dest)
      #dest = StringIO.new
      dest << "////// AUTOGENERATED VIEW FROM #{srcpath.basename.to_s} /////\n"
      dest << "#{view_name}.prototype.generateHTML = function() {\n"
      source = File.new(srcpath).read
      listener = SailsXML::SailsXMLStreamListener.new("__sout", dest)
      parser = REXML::Parsers::StreamParser.new(source, listener)
      parser.parse
      
      listener.eof
      dest << "return __sout; }\n"
      #dest.seek(0, IO::SEEK_SET)
      #return the result
      #return dest.read
      dest
    end
  end
  
  
  class AutoBuilder < Builder
    def compile_directory(path, recursive = false)
      dir = Pathname.new(path)
      #puts "traversing path #{dir}"
      dest_path = format_dest_path(dir)
      
      name_of_sail = Inflector::camelize(dir.basename.to_s)
      config = Config::Sail.new(dir, dest_path, name_of_sail)
      dir.children.each do |src_path|
        if src_path.directory?
          compile_directory(src_path, true) if recursive && include_directory?(src_path)
        else
          if compile_as_view?(config, src_path)
            config.views.push(Config::View.new(config, src_path))
          elsif compile_into_build?(config, src_path)
            config.other_files.push(Config::OtherFile.new(config, src_path))
          end
        end
      end
      build_sail(config)
    end
    
    protected
    def include_directory?(path)
      if (path.basename.to_s =~ /^\./)
        return false
      else
        return true
      end
    end
    def format_dest_path(src_path)
      dir = src_path.directory? ? src_path : src_path.dirname
      dir + (base_sail_name(src_path) + ".built.js")
    end
    def base_sail_name(src_path)
      dir = src_path.directory? ? src_path : src_path.dirname
      dir.basename.to_s
    end
    def compile_as_view?(config, path)
      return(true) if path.basename.to_s =~ /\.view\.html$/
      return false
    end
    def compile_into_build?(config, path)
      return false if path == config.dest_path
      return(true) if path.basename.to_s =~ /\.js$/
      return false
    end
  end
end

throw "Expected at least one argument which is the directory to compile" if ARGV.empty?

builder = Sails::AutoBuilder.new
builder.compile_directory(ARGV[0], true)