// WARNING: This file was generated automatically by the Sauve Sails builder
// Do not make modifications to this file.  Modify other files in this directory
// and run the builder to recompile.

//contents of 'my_table.controller.js'
sails.MyTableController = function()
{
   Log.msg(this)
   //this.model = new sails.FunlingModel();
   this.view = new sails.MyTableView()
}
sails.MyTableController.prototype = {
   create : function(elemid)
   {
      var elem = window.document.getElementById(elemid)
      this.view.renderHTML(function(html) { Log.msg(html); elem.innerHTML = html; })
      //this.view.renderHTML(function(html) { elem.innerHTML = html; })
      this.view.dom.caption.innerHTML = "This is a simple table example."
   }
}
//contents of 'my_table.model.js'
//contents of 'my_table.view.js'
var MyTableView = sails.MyTableView = function()
{
   //this calls the default Sails View constructor with 'this' object as a parameter
   //by doing this, and also setting sails.MyTable's prototype
   // to Sail.View's, we have an object that operates just like the default View
   //this is necessary for the object to inherit the behavior of a standard Sail
   //you may add your own methods to sails.MyTable, but already
   //you have a view that is perfectly capable of being manipulated
   HTMLSail.View.call(this);
}
sails.MyTableView.prototype = HTMLSail.View.prototype

////// AUTOGENERATED VIEW FROM my_table.view.html /////
MyTableView.prototype.generateHTML = function() {
__sout=""+
"<table"+
" id=\""+
this.defField("root",{})+
"\""+
" >"+
"\n   "+
"<caption"+
" id=\""+
this.defField("caption",{})+
"\""+
" >"+
" "+
"</caption>"+
"\n   "+
"<tr"+
" id=\""+
this.defField("headrow",{insertion : "after"})+
"\""+
"<td"+
" >"+
"SUPER!!!!!"+
"</td>"+
"</tr>"+
"\n"+
"</table>"+
"\n"
return __sout; }

